SOI: add special case for 47G_4, temporarily switch off retiling

diff --git a/.github/workflows/soi_parse.yml b/.github/workflows/soi_parse.yml
--- a/.github/workflows/soi_parse.yml
+++ b/.github/workflows/soi_parse.yml
@@ -105,121 +105,119 @@ jobs:
         run: |
           maps/SOI/generate_lists.sh
 
-      - name: Check for retile work
-        id: retile_work
-        run: |
-          if [[ "$(gsutil ls gs://soi_data/to_retile.txt 2>/dev/null)" == "" ]]; then
-            echo "AVAILABLE=false" >> $GITHUB_OUTPUT
-          else
-            mkdir -p data
-            gsutil -m cp gs://soi_data/to_retile.txt data/to_retile.txt
-            gsutil -m cp gs://soi_data/index.geojson data/index.geojson
-            echo "AVAILABLE=true" >> $GITHUB_OUTPUT
-          fi
-      - name: Restore run data from cache
-        uses: ramSeraph/cache-always@v0.0.1
-        with:
-          path: |
-            staging/
-            export/
-            !export/pmtiles/*
-          key:  soi-gcs-v5-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
-          restore-keys: |
-            soi-gcs-v5-${{ steps.date.outputs.date }}-${{ github.run_number }}-
-            soi-gcs-v5-${{ steps.date.outputs.date }}-
+          #- name: Check for retile work
+          #  id: retile_work
+          #  run: |
+          #    if [[ "$(gsutil ls gs://soi_data/to_retile.txt 2>/dev/null)" == "" ]]; then
+          #      echo "AVAILABLE=false" >> $GITHUB_OUTPUT
+          #    else
+          #      mkdir -p data
+          #      gsutil -m cp gs://soi_data/to_retile.txt data/to_retile.txt
+          #      gsutil -m cp gs://soi_data/index.geojson data/index.geojson
+          #      echo "AVAILABLE=true" >> $GITHUB_OUTPUT
+          #    fi
+          #- name: Restore run data from cache
+          #  uses: ramSeraph/cache-always@v0.0.1
+          #  with:
+          #    path: |
+          #      staging/
+          #      export/
+          #      !export/pmtiles/*
+          #    key:  soi-gcs-v5-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
+          #    restore-keys: |
+          #      soi-gcs-v5-${{ steps.date.outputs.date }}-${{ github.run_number }}-
+          #      soi-gcs-v5-${{ steps.date.outputs.date }}-
 
-      - name: Download pmtiles
-        id: download-pmtiles
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          ls staging || true
-          if [[ -e staging/all_done ]]; then
-            echo "download already done.. shortcircuiting"
-            exit 0
-          fi
-          source .github/actions/releaser/rfuncs.sh
-          mkdir -p export/pmtiles
-          release_id="$(get_release_id soi-latest)"
-          download_release_assets $release_id export/pmtiles
-          mkdir -p staging
+          #- name: Download pmtiles
+          #  id: download-pmtiles
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  env:
+          #    GH_TOKEN: ${{ github.token }}
+          #  run: |
+          #    ls staging || true
+          #    if [[ -e staging/all_done ]]; then
+          #      echo "download already done.. shortcircuiting"
+          #      exit 0
+          #    fi
+          #    source .github/actions/releaser/rfuncs.sh
+          #    mkdir -p export/pmtiles
+          #    release_id="$(get_release_id soi-latest)"
+          #    download_release_assets $release_id export/pmtiles
+          #    mkdir -p staging
 
-      - name: Retile sheets
-        id: retile-sheets
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        run: |
-          if [[ -e staging/retiling_done ]]; then
-            exit 0
-          fi
-          mkdir -p export/tiles/
-          mkdir -p staging/tiles/
-          mkdir -p staging/pmtiles/
-          docker run -d --name retiler -v $(pwd):/code -w /code -e GOOGLE_APPLICATION_CREDENTIALS=gauth.json soi-parse maps/SOI/retile.py data/to_retile.txt
-          docker logs -f retiler
-          exit_code=$(docker inspect retiler --format='{{.State.ExitCode}}')
-          if [[ "$exit_code" != "0" ]]; then
-            echo "exit_code: $exit_code"
-            exit 1
-          fi
-          rm -rf staging/gtiffs/* || true
-          rm -rf export/gtiffs/* || true
-          touch staging/retiling_done
-        timeout-minutes: 600
+          #- name: Retile sheets
+          #  id: retile-sheets
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  run: |
+          #    if [[ -e staging/retiling_done ]]; then
+          #      exit 0
+          #    fi
+          #    mkdir -p export/tiles/
+          #    mkdir -p staging/tiles/
+          #    mkdir -p staging/pmtiles/
+          #    docker run -d --name retiler -v $(pwd):/code -w /code -e GOOGLE_APPLICATION_CREDENTIALS=gauth.json soi-parse maps/SOI/retile.py data/to_retile.txt
+          #    docker logs -f retiler
+          #    exit_code=$(docker inspect retiler --format='{{.State.ExitCode}}')
+          #    if [[ "$exit_code" != "0" ]]; then
+          #      echo "exit_code: $exit_code"
+          #      exit 1
+          #    fi
+          #    rm -rf staging/gtiffs/* || true
+          #    rm -rf export/gtiffs/* || true
+          #    touch staging/retiling_done
+          #  timeout-minutes: 600
 
-      - name: Partition pmtiles
-        id: partition-pmtiles
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        run: |
-          if [[ -e staging/all_done ]]; then
-            exit 0
-          fi
-          df -h .
-          du -h .
-          docker run -d --name partitioner -v $(pwd):/code -w /code soi-parse maps/SOI/partition.py
-          docker logs -f partitioner
-          exit_code=$(docker inspect partitioner --format='{{.State.ExitCode}}')
-          if [[ "$exit_code" != "0" ]]; then
-            echo "exit_code: $exit_code"
-            exit 1
-          fi
-          rm -rf export/*
-          staging_files=$(find staging/pmtiles -type f)
-          echo "staging_files: $staging_files"
-          echo "release_files<<EOF" >> $GITHUB_OUTPUT
-          echo "$staging_files" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-          touch staging/all_done
-          
+          #- name: Partition pmtiles
+          #  id: partition-pmtiles
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  run: |
+          #    if [[ -e staging/all_done ]]; then
+          #      exit 0
+          #    fi
+          #    docker run -d --name partitioner -v $(pwd):/code -w /code soi-parse maps/SOI/partition.py
+          #    docker logs -f partitioner
+          #    exit_code=$(docker inspect partitioner --format='{{.State.ExitCode}}')
+          #    if [[ "$exit_code" != "0" ]]; then
+          #      echo "exit_code: $exit_code"
+          #      exit 1
+          #    fi
+          #    rm -rf export/*
+          #    staging_files=$(find staging/pmtiles -type f)
+          #    echo "staging_files: $staging_files"
+          #    echo "release_files<<EOF" >> $GITHUB_OUTPUT
+          #    echo "$staging_files" >> $GITHUB_OUTPUT
+          #    echo "EOF" >> $GITHUB_OUTPUT
+          #    touch staging/all_done
+          #    
 
-      - name: Push pmtiles
-        env:
-          GH_TOKEN: ${{ github.token }}
-        id: push-pmtiles
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        uses: ./.github/actions/releaser
-        with:
-          name: "SOI Open Series Maps"
-          tag_name: soi-latest
-          assets: ${{ steps.partition-pmtiles.outputs.release_files }} 
-          body: "SOI Open Series Maps as partitioned PMTiles."
-          gh_token: ${{ secrets.github_token }}
+          #- name: Push pmtiles
+          #  env:
+          #    GH_TOKEN: ${{ github.token }}
+          #  id: push-pmtiles
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  uses: ./.github/actions/releaser
+          #  with:
+          #    name: "SOI Open Series Maps"
+          #    tag_name: soi-latest
+          #    assets: ${{ steps.partition-pmtiles.outputs.release_files }} 
+          #    body: "SOI Open Series Maps as partitioned PMTiles."
+          #    gh_token: ${{ secrets.github_token }}
 
-      - name: Cleanup
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        run: |
-          rm -rf staging/*
-          gsutil rm gs://soi_data/to_retile.txt
+          #- name: Cleanup
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  run: |
+          #    rm -rf staging/*
+          #    gsutil rm gs://soi_data/to_retile.txt
 
-      - name: Setup fly tools
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        uses: superfly/flyctl-actions/setup-flyctl@1.5
+          #- name: Setup fly tools
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  uses: superfly/flyctl-actions/setup-flyctl@1.5
 
-      - name: Restart Fly Server
-        if: steps.retile_work.outputs.AVAILABLE == 'true'
-        run: |
-          flyctl scale count 0 --app soi -y
-          flyctl scale count 1 --app soi -y
+          #- name: Restart Fly Server
+          #  if: steps.retile_work.outputs.AVAILABLE == 'true'
+          #  run: |
+          #    flyctl scale count 0 --app soi -y
+          #    flyctl scale count 1 --app soi -y
  
 
   SOI-Parse-Failure-Notify:
